repos:
  - repo: local
    hooks:
      - id: jupyter-clean
        name: Clean Jupyter Notebook outputs
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        files: \.ipynb$
        language: system